export const SITE = {
  nomCommercial: "N'en fais pas tout un fromage",
  raisonSociale: "N'EN FAIS PAS TOUT UN FROMAGE",
  formeJuridique: "SARL (Société à responsabilité limitée)",
  capitalSocial: "1 000 €",
  siren: "939 719 688",
  siret: "939 719 688 00011",
  tva: "FR61939719688",
  regimeTva: "TVA au taux réduit de 5,5 % (produits alimentaires)",
  rcs: "RCS Brest 939 719 688",
  naf: "4781Z — Commerce de détail alimentaire sur éventaires et marchés",
  activite: "Crèmerie, fromagerie",
  gerant: "Maugan LE GAC",
  directeurPublication: "Maugan LE GAC",
  adresse: "Le Veuzit, 29620 Plouégat-Guérand",
  codePostal: "29620",
  ville: "Plouégat-Guérand",
  region: "Bretagne",
  email: "mauganlegac2@gmail.com",
  telephone: "06 13 87 07 17",
  instagram: "https://www.instagram.com/nenfaispastoutunfromage/",
  facebook: "https://www.facebook.com/people/Nen-fais-pas-tout-un-fromage/61569658432835/",
  hebergeur: "Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA",
  baseDonnees: "Supabase (Supabase Inc., San Francisco, CA, USA)",
  paiement: "Stripe (Stripe Payments Europe Ltd., Dublin, Irlande)",
  emailService: "Resend (Resend Inc., San Francisco, CA, USA)",
  url: "https://nenfaitpastoutunfromage.com",
  description:
    "Fromagerie artisanale itinérante en Bretagne. Découvrez nos fromages affinés, consultez les marchés de la semaine et commandez en click & collect.",
} as const;
